### ISSUE TITLE
Crashes Client

### ISSUE THREAD

**Issue by Syrdaimons** [SamRaven2/DualCraft#1]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 08/04/15 14:31
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayer.isSneaking()Z
    at com.bats.dualcraft.handler.WorldEventHandler.onPlayerInteract(WorldEventHandler.java:27)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_WorldEventHandler_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1434)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.bats.dualcraft.handler.WorldEventHandler.onPlayerInteract(WorldEventHandler.java:27)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_WorldEventHandler_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1434)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Syrdaimons'/429, l='MpServer', x=-192.50, y=66.62, z=256.50]]
    Chunk stats: MultiplayerChunkCache: 569, 569
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-188,64,248), Chunk: (at 4,4,8 in -12,15; contains blocks -192,0,240 to -177,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 172 game time, 172 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 158 total; [EntitySheep['Sheep'/58, l='MpServer', x=-261.38, y=72.00, z=180.59], EntitySheep['Sheep'/59, l='MpServer', x=-264.50, y=71.00, z=179.50], EntitySheep['Sheep'/60, l='MpServer', x=-268.50, y=71.00, z=180.50], EntitySheep['Sheep'/61, l='MpServer', x=-263.71, y=71.00, z=186.14], EntityZombie['Zombie'/62, l='MpServer', x=-268.50, y=41.00, z=263.50], EntityBat['Bat'/63, l='MpServer', x=-243.56, y=20.54, z=283.55], EntityBat['Bat'/64, l='MpServer', x=-265.09, y=29.70, z=291.75], EntityBat['Bat'/65, l='MpServer', x=-257.70, y=33.42, z=331.64], EntityBat['Bat'/66, l='MpServer', x=-251.69, y=37.44, z=331.59], EntitySheep['Sheep'/72, l='MpServer', x=-251.50, y=71.00, z=183.50], EntitySheep['Sheep'/73, l='MpServer', x=-251.50, y=72.00, z=180.50], EntitySheep['Sheep'/74, l='MpServer', x=-252.50, y=72.00, z=178.50], EntitySheep['Sheep'/76, l='MpServer', x=-241.22, y=70.00, z=196.22], EntitySheep['Sheep'/77, l='MpServer', x=-242.81, y=70.00, z=197.81], EntityBat['Bat'/86, l='MpServer', x=-257.21, y=33.73, z=289.59], EntitySkeleton['Skeleton'/87, l='MpServer', x=-245.50, y=29.00, z=290.50], EntityChicken['Chicken'/88, l='MpServer', x=-241.60, y=64.00, z=308.08], EntitySpider['Spider'/89, l='MpServer', x=-248.34, y=19.81, z=327.81], EntitySkeleton['Skeleton'/90, l='MpServer', x=-246.50, y=24.00, z=334.50], EntitySheep['Sheep'/126, l='MpServer', x=-237.72, y=70.00, z=192.56], EntitySheep['Sheep'/127, l='MpServer', x=-237.22, y=70.00, z=196.10], EntitySheep['Sheep'/128, l='MpServer', x=-229.22, y=63.00, z=256.50], EntitySheep['Sheep'/129, l='MpServer', x=-230.81, y=63.00, z=256.50], EntitySheep['Sheep'/130, l='MpServer', x=-228.50, y=63.00, z=260.50], EntitySheep['Sheep'/131, l='MpServer', x=-230.50, y=63.00, z=260.50], EntityChicken['Chicken'/134, l='MpServer', x=-234.50, y=64.00, z=318.50], EntityChicken['Chicken'/135, l='MpServer', x=-237.50, y=64.00, z=319.50], EntityChicken['Chicken'/136, l='MpServer', x=-238.50, y=64.00, z=315.50], EntityBat['Bat'/137, l='MpServer', x=-230.93, y=14.24, z=335.26], EntityBat['Bat'/138, l='MpServer', x=-229.02, y=12.25, z=333.46], EntityBat['Bat'/139, l='MpServer', x=-234.54, y=19.39, z=325.60], EntityCreeper['Creeper'/140, l='MpServer', x=-236.66, y=21.76, z=326.17], EntityCreeper['Creeper'/141, l='MpServer', x=-233.50, y=19.00, z=326.50], EntityCreeper['Creeper'/142, l='MpServer', x=-235.69, y=20.00, z=325.06], EntityZombie['Zombie'/154, l='MpServer', x=-237.50, y=24.00, z=336.50], EntitySheep['Sheep'/180, l='MpServer', x=-199.78, y=63.00, z=212.22], EntitySheep['Sheep'/181, l='MpServer', x=-198.00, y=64.00, z=215.46], EntitySheep['Sheep'/182, l='MpServer', x=-198.50, y=63.00, z=212.28], EntitySheep['Sheep'/183, l='MpServer', x=-195.63, y=63.00, z=210.25], EntityBat['Bat'/184, l='MpServer', x=-193.17, y=14.78, z=250.72], EntitySquid['Squid'/185, l='MpServer', x=-198.63, y=58.31, z=318.34], EntitySquid['Squid'/186, l='MpServer', x=-204.31, y=56.78, z=319.22], EntityBat['Bat'/187, l='MpServer', x=-206.72, y=28.39, z=322.36], EntitySquid['Squid'/193, l='MpServer', x=-208.50, y=61.38, z=317.31], EntityCreeper['Creeper'/213, l='MpServer', x=-188.96, y=18.00, z=251.63], EntityBat['Bat'/214, l='MpServer', x=-189.53, y=21.18, z=323.46], EntityBat['Bat'/215, l='MpServer', x=-169.91, y=19.10, z=335.34], EntityZombie['Zombie'/216, l='MpServer', x=-189.50, y=21.00, z=323.50], EntityCreeper['Creeper'/217, l='MpServer', x=-183.50, y=21.00, z=327.50], EntityCreeper['Creeper'/218, l='MpServer', x=-183.97, y=21.00, z=324.59], EntitySkeleton['Skeleton'/219, l='MpServer', x=-186.35, y=21.00, z=323.48], EntitySkeleton['Skeleton'/220, l='MpServer', x=-188.50, y=21.00, z=323.50], EntitySkeleton['Skeleton'/241, l='MpServer', x=-173.50, y=31.00, z=241.50], EntitySquid['Squid'/257, l='MpServer', x=-149.59, y=57.34, z=215.75], EntitySquid['Squid'/258, l='MpServer', x=-154.38, y=61.03, z=214.50], EntitySquid['Squid'/259, l='MpServer', x=-153.34, y=59.19, z=214.81], EntitySquid['Squid'/260, l='MpServer', x=-157.34, y=61.34, z=225.13], EntitySquid['Squid'/261, l='MpServer', x=-147.31, y=60.78, z=214.03], EntitySquid['Squid'/262, l='MpServer', x=-149.38, y=57.06, z=219.53], EntitySquid['Squid'/263, l='MpServer', x=-146.72, y=59.38, z=215.91], EntitySquid['Squid'/264, l='MpServer', x=-151.03, y=60.19, z=214.97], EntitySquid['Squid'/265, l='MpServer', x=-143.72, y=61.38, z=213.69], EntitySquid['Squid'/266, l='MpServer', x=-143.34, y=60.31, z=210.87], EntitySquid['Squid'/267, l='MpServer', x=-150.47, y=51.06, z=237.22], EntitySquid['Squid'/268, l='MpServer', x=-147.91, y=52.31, z=237.88], EntitySquid['Squid'/269, l='MpServer', x=-154.50, y=52.19, z=243.31], EntitySquid['Squid'/270, l='MpServer', x=-153.91, y=51.00, z=239.53], EntitySquid['Squid'/271, l='MpServer', x=-152.75, y=51.91, z=246.13], EntitySquid['Squid'/272, l='MpServer', x=-147.09, y=50.06, z=246.94], EntitySquid['Squid'/273, l='MpServer', x=-151.94, y=51.97, z=243.19], EntitySquid['Squid'/274, l='MpServer', x=-143.97, y=54.41, z=243.44], EntitySquid['Squid'/275, l='MpServer', x=-147.13, y=50.38, z=248.50], EntitySquid['Squid'/276, l='MpServer', x=-144.56, y=52.19, z=240.66], EntitySquid['Squid'/277, l='MpServer', x=-144.37, y=51.81, z=237.78], EntitySquid['Squid'/278, l='MpServer', x=-150.25, y=54.38, z=238.25], EntitySquid['Squid'/279, l='MpServer', x=-152.50, y=50.31, z=244.19], EntitySquid['Squid'/280, l='MpServer', x=-151.56, y=50.41, z=245.28], EntitySquid['Squid'/289, l='MpServer', x=-138.13, y=59.34, z=216.91], EntitySquid['Squid'/290, l='MpServer', x=-143.56, y=60.75, z=215.44], EntitySquid['Squid'/291, l='MpServer', x=-133.03, y=53.34, z=219.25], EntitySquid['Squid'/292, l='MpServer', x=-145.53, y=52.25, z=237.16], EntitySquid['Squid'/293, l='MpServer', x=-130.16, y=50.38, z=235.03], EntitySquid['Squid'/294, l='MpServer', x=-137.88, y=53.38, z=235.44], EntitySquid['Squid'/295, l='MpServer', x=-137.16, y=52.97, z=224.16], EntitySquid['Squid'/296, l='MpServer', x=-129.59, y=49.06, z=237.03], EntitySquid['Squid'/297, l='MpServer', x=-134.13, y=53.38, z=227.97], EntitySquid['Squid'/298, l='MpServer', x=-135.84, y=53.28, z=225.28], EntitySquid['Squid'/299, l='MpServer', x=-138.13, y=51.06, z=228.78], EntitySquid['Squid'/300, l='MpServer', x=-142.59, y=51.34, z=228.19], EntitySquid['Squid'/301, l='MpServer', x=-145.41, y=52.38, z=242.88], EntitySquid['Squid'/302, l='MpServer', x=-141.16, y=52.25, z=236.59], EntitySquid['Squid'/303, l='MpServer', x=-144.81, y=48.97, z=237.94], EntitySquid['Squid'/304, l='MpServer', x=-146.91, y=54.34, z=242.44], EntitySquid['Squid'/305, l='MpServer', x=-142.44, y=54.34, z=242.81], EntitySquid['Squid'/306, l='MpServer', x=-142.31, y=51.34, z=240.44], EntitySquid['Squid'/307, l='MpServer', x=-141.41, y=54.34, z=238.84], EntitySkeleton['Skeleton'/308, l='MpServer', x=-143.50, y=20.00, z=325.50], EntityBat['Bat'/330, l='MpServer', x=-119.47, y=35.68, z=317.61], EntityZombie['Zombie'/459, l='MpServer', x=-198.50, y=13.00, z=251.50], EntityCreeper['Creeper'/475, l='MpServer', x=-271.50, y=39.00, z=246.50], EntityCreeper['Creeper'/477, l='MpServer', x=-272.50, y=39.00, z=246.50], EntityCreeper['Creeper'/479, l='MpServer', x=-270.50, y=39.00, z=248.50], EntityCreeper['Creeper'/480, l='MpServer', x=-271.50, y=39.00, z=251.50], EntityCreeper['Creeper'/481, l='MpServer', x=-272.79, y=38.78, z=252.78], EntitySkeleton['Skeleton'/493, l='MpServer', x=-186.50, y=19.00, z=258.50], EntitySkeleton['Skeleton'/494, l='MpServer', x=-185.50, y=19.00, z=257.50], EntitySkeleton['Skeleton'/495, l='MpServer', x=-189.50, y=19.00, z=260.50], EntityClientPlayerMP['Syrdaimons'/429, l='MpServer', x=-192.50, y=66.62, z=256.50], EntityEnderman['Enderman'/538, l='MpServer', x=-192.94, y=20.00, z=313.25], EntityFallingBlock['Falling Block'/2598, l='MpServer', x=-131.50, y=27.37, z=395.50], EntityFallingBlock['Falling Block'/2601, l='MpServer', x=-116.50, y=5.20, z=172.50], EntityFallingBlock['Falling Block'/2606, l='MpServer', x=-119.50, y=6.20, z=172.50], EntityFallingBlock['Falling Block'/2609, l='MpServer', x=-120.50, y=6.20, z=171.50], EntityFallingBlock['Falling Block'/2610, l='MpServer', x=-120.50, y=5.20, z=170.50], EntityFallingBlock['Falling Block'/2613, l='MpServer', x=-121.50, y=6.20, z=171.50], EntityFallingBlock['Falling Block'/2906, l='MpServer', x=-318.50, y=26.16, z=259.50], EntityFallingBlock['Falling Block'/2907, l='MpServer', x=-317.50, y=25.16, z=260.50], EntityFallingBlock['Falling Block'/2908, l='MpServer', x=-318.50, y=26.16, z=260.50], EntityFallingBlock['Falling Block'/2909, l='MpServer', x=-318.50, y=26.16, z=261.50], EntityFallingBlock['Falling Block'/2910, l='MpServer', x=-319.50, y=26.16, z=260.50], EntityFallingBlock['Falling Block'/2911, l='MpServer', x=-319.50, y=26.16, z=261.50], EntityItem['item.item.seeds'/887, l='MpServer', x=-219.88, y=63.13, z=249.44], EntityFallingBlock['Falling Block'/3151, l='MpServer', x=-213.50, y=58.93, z=129.50], EntityFallingBlock['Falling Block'/3152, l='MpServer', x=-212.50, y=58.93, z=129.50], EntityFallingBlock['Falling Block'/3153, l='MpServer', x=-211.50, y=58.93, z=129.50], EntityFallingBlock['Falling Block'/3154, l='MpServer', x=-214.50, y=58.93, z=129.50], EntityCreeper['Creeper'/1166, l='MpServer', x=-156.50, y=24.00, z=263.50], EntityCreeper['Creeper'/1167, l='MpServer', x=-156.50, y=24.00, z=264.50], EntityZombie['Zombie'/1188, l='MpServer', x=-244.50, y=29.00, z=289.50], EntityFallingBlock['Falling Block'/3241, l='MpServer', x=-118.50, y=7.85, z=172.50], EntityFallingBlock['Falling Block'/3246, l='MpServer', x=-113.50, y=6.85, z=181.50], EntityFallingBlock['Falling Block'/3248, l='MpServer', x=-114.50, y=6.85, z=181.50], EntityFallingBlock['Falling Block'/3250, l='MpServer', x=-114.50, y=6.85, z=180.50], EntityZombie['Zombie'/1223, l='MpServer', x=-259.91, y=12.00, z=270.41], EntityZombie['Zombie'/1224, l='MpServer', x=-258.50, y=12.00, z=267.50], EntityZombie['Zombie'/1225, l='MpServer', x=-260.82, y=12.00, z=270.55], EntitySpider['Spider'/1419, l='MpServer', x=-164.50, y=31.00, z=331.50], EntityFallingBlock['Falling Block'/3476, l='MpServer', x=-318.50, y=27.93, z=259.50], EntityFallingBlock['Falling Block'/3477, l='MpServer', x=-317.50, y=26.93, z=260.50], EntityFallingBlock['Falling Block'/3478, l='MpServer', x=-318.50, y=27.93, z=260.50], EntityFallingBlock['Falling Block'/3479, l='MpServer', x=-318.50, y=27.93, z=261.50], EntityFallingBlock['Falling Block'/3480, l='MpServer', x=-319.50, y=27.93, z=260.50], EntityFallingBlock['Falling Block'/3481, l='MpServer', x=-319.50, y=27.93, z=261.50], EntityFallingBlock['Falling Block'/3600, l='MpServer', x=-176.50, y=14.67, z=363.50], EntityFallingBlock['Falling Block'/3619, l='MpServer', x=-113.50, y=7.65, z=172.50], EntityFallingBlock['Falling Block'/3621, l='MpServer', x=-115.50, y=7.65, z=181.50], EntityFallingBlock['Falling Block'/3622, l='MpServer', x=-114.50, y=7.65, z=182.50], EntityFallingBlock['Falling Block'/3623, l='MpServer', x=-116.50, y=7.65, z=181.50], EntityFallingBlock['Falling Block'/3628, l='MpServer', x=-111.50, y=7.65, z=174.50], EntityFallingBlock['Falling Block'/3724, l='MpServer', x=-317.50, y=28.67, z=260.50], EntityFallingBlock['Falling Block'/3738, l='MpServer', x=-115.50, y=9.39, z=181.50], EntityFallingBlock['Falling Block'/3739, l='MpServer', x=-116.50, y=9.39, z=181.50], EntityFallingBlock['Falling Block'/3740, l='MpServer', x=-115.50, y=13.74, z=182.50], EntityFallingBlock['Falling Block'/3741, l='MpServer', x=-117.50, y=13.74, z=181.50], EntityFallingBlock['Falling Block'/1938, l='MpServer', x=-318.50, y=23.55, z=260.50], EntityFallingBlock['Falling Block'/1939, l='MpServer', x=-318.50, y=23.55, z=261.50], EntityFallingBlock['Falling Block'/1940, l='MpServer', x=-319.50, y=23.55, z=260.50], EntityFallingBlock['Falling Block'/1941, l='MpServer', x=-319.50, y=23.55, z=261.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 154869184 bytes (147 MB) / 901251072 bytes (859 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 4 mods loaded, 4 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1291} [Forge Mod Loader](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1291} [Minecraft Forge](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DualCraft{1.0} [DualCraft](DualCraft-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: forge-10.13.2.1291
    LWJGL: 2.9.1
    OpenGL: ATI Radeon HD 4800 Series GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by SamRaven2** [comment]
Could you possibly go over the steps to reproduce, I am unable to determine the cause currently.

**Comment by SamRaven2** [comment]
So I was able to reproduce. For whatever reason it's an issue with the artifact from the 1.0.0 build. I'll see if re-building as version 1.0.1 fixes it.

**Comment by SamRaven2** [comment]
Version 1.0.1 seems to have fixed it, sorry for the inconvenience.
